#!/usr/bin/perl -w

# Generate usys.S, the stubs for syscalls.

print "# generated by usys.pl - do not edit.n";
print "# t6 holds the errno value from the kernel\n";
print "# and t5 gets tromped on as well.\n";

print "#include \"../../include/xv6/syscall.h\"\n";

my $labelnum= 1;

sub entry {
    my $name = shift;
    print ".global $name\n";
    print "${name}:\n";
    print " li a7, SYS_${name}\n";
    print " ecall\n";
    print " beq t6,zero,.L$labelnum\n";	# Don't set errno to zero
    print " la t5,errno\n";
    print " sw t6,0(t5)\n";
    print ".L$labelnum:\n"; $labelnum++;
    print " ret\n";
}
	
entry("fork");
entry("_exit");
entry("wait");
entry("pipe");
entry("read");
entry("write");
entry("close");
entry("kill");
entry("exec");
entry("open");
entry("mknod");
entry("unlink");
entry("xv6fstat");
entry("link");
entry("mkdir");
entry("chdir");
entry("dup");
entry("getpid");
entry("sbrk");
entry("sleep");
entry("uptime");
entry("time");
entry("lseek");
entry("ioctl");
entry("fchdir");
