all:
	(cd xv6; make)
	(cd test; make)
	(cd simple; make)

install:
	(cd xv6; make install)
	(cd test; make install)
	(cd simple; make install)

clean:
	(cd xv6; make clean)
	(cd test; make clean)
	(cd simple; make clean)
