all:
	(cd xv6; make)
	(cd test; make)
	(cd simple; make)
	(cd s; make)
	(cd wish; make)
	(cd v7sh; make)

install:
	(cd xv6; make install)
	(cd test; make install)
	(cd simple; make install)
	(cd s; make install)
	(cd wish; make install)
	(cd v7sh; make install)

clean:
	(cd xv6; make clean)
	(cd test; make clean)
	(cd simple; make clean)
	(cd s; make clean)
	(cd wish; make clean)
	(cd v7sh; make clean)
